export const EXPENSE_CATEGORIES = [
    // Vendors / Ingredients
    'Restaurant Depot',
    "Sam's Club",
    'Costco',
    'Tan Binh',
    'Viet Hoa',
    'Webstaurant',
    'Amazon',
    'Juniors Supermarket',
    'Lollicup',
    'Bossen',
    'HMart',
    'Hong Kong Market',
    'VegeMarket',
    "Sun's Wholesale",
    'KingSeal',
    'Alcohol',
    'Cambie',
    'Ben E. Keith',
    'Walmart',
    'HEB',
    'Target',
    'AliExpress',
    // Utilities
    'Electricity',
    'Spectrum',
    'Texas Gas',
    'AT&T',
    // Maintenance
    'Home Depot',
    "Lowe's",
    'Maintenance',
    'Locksmith',
    'ADT Security',
    // Office / Supplies
    'Office Depot',
    'Supplies',
    'Decorations & Ambience',
    'Printing',
    // Software / Subscriptions
    'QuickBooks',
    'OpenAI',
    'Claude',
    'Apple',
    'Menusifu',
    'Subscription',
    // Insurance
    'GEICO',
    'Hartford',
    // Marketing
    'Facebook/Meta',
    // Transportation / Fuel
    'Uber',
    'U-Haul',
    'Enterprise',
    'AutoZone',
    'BlueWave',
    "Buc-ee's",
    "Love's",
    'Phillips 66',
    'Shell',
    'Texan',
    '7-Eleven',
    'Circle K',
    'Exxon',
    'Booking/Hotel',
    // Meals
    'Meal',
    // Uniform
    'Uniform',
    // Regulatory / Fees
    'TDLR',
    'Food Handler',
    'City of Edinburg',
    'Greater PHA',
    'McAllen TX',
    'The Touch On',
    'Event Vendor Fees',
    'Sales Tax',
    'Bank Fee',
    'Merchant Fee',
    'Rent',
    // Payroll
    'Payroll',
    'Payroll Tax',
    'Payroll Fee',
    // Banking / Transfers
    'Owner Withdraw',
    'Online Sales',
    'Cash Deposit',
    'Deposit',
    // POS / Delivery
    'Square',
    'DoorDash',
    'Grubhub',
    'Amex',
    'Discover',
    // Credit Card Payments
    'Credit Card Payment',
    // Catch-all
    'Other/Review',
];
